# name: deploy-payments

# on:
#   push:
#     branches:
#       - master
#     paths:
#       - "payments/**"
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - run: cd payments && docker build -t andy411/payments .
#       - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
#         env:
#           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#       - run: docker push andy411/payments
#       - uses: digitalocean/action-doctl@v2
#         with:
#           token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
#       - run: doctl kubernetes cluster kubeconfig save d72f92b5-f842-4688-9388-308856a724ba
#       - run: kubectl rollout restart deployment payments-depl
